local m = peripheral.wrap("right")
m.clear()
 
m.setTextScale(0.5)
m.setCursorPos(1,1)
m.write("Is this the Region, this the Soil, the Clime,")
m.setCursorPos(1,2)
m.write("Said then the lost Arch-Angel, this the seat")
m.setCursorPos(1,3)
m.write("That we must change for Heav'n, this mournful gloom")
m.setCursorPos(1,4)
m.write("For that celestial light? Be it so, since he")
m.setCursorPos(1,5)
m.write("Who now is Sovran can dispose and bid")
m.setCursorPos(1,6)
m.write("What shall be right: fardest from him is best")
m.setCursorPos(1,7)
m.write("Whom reason hath equald, force hath made supream")
m.setCursorPos(1,8)
m.write("Above his equals. Farewel happy Fields")
m.setCursorPos(1,9)
m.write("Where Joy for ever dwells: Hail horrours, hail")
m.setCursorPos(1,10)
m.write("Infernal world, and thou profoundest Hell")
m.setCursorPos(1,11)
m.write("Receive thy new Possessor: One who brings")
m.setCursorPos(1,12)
m.write("A mind not to be chang'd by Place or Time.")
m.setCursorPos(1,13)
m.write("The mind is its own place, and in it self")
m.setCursorPos(1,14)
m.write("Can make a Heav'n of Hell, a Hell of Heav'n.") 
m.setCursorPos(1,15)
m.write("What matter where, if I be still the same,")
m.setCursorPos(1,16)
m.write("And what I should be, all but less then he")
m.setCursorPos(1,17)
m.write("Whom Thunder hath made greater? Here at least")
m.setCursorPos(1,18)
m.write("We shall be free; th' Almighty hath not built")
m.setCursorPos(1,19)
m.write("Here for his envy, will not drive us hence:")
m.setCursorPos(1,20)
m.write("Here we may reign secure, and in my choyce")
m.setCursorPos(1,21)
m.write("To reign is worth ambition though in Hell:")
m.setCursorPos(1,22)
m.write("Better to reign in Hell, then serve in Heav'n.")
